#!/bin/bash
#Designed to help the Ops for deploying the apps

PATH1=` ls -ltr /app/dre/thirdparty/apache-tomcat-9.0.10/webapps| awk '{print $11}'| sed '1d'|sed -n -e 1p -e 3p -e 5p -e 7p|cut -d/ -f 1,2,3,4,5| sed -n '1p' `
PATH2=` ls -ltr /app/dre/thirdparty/apache-tomcat-9.0.10/webapps| awk '{print $11}'| sed '1d'|sed -n -e 1p -e 3p -e 5p -e 7p|cut -d/ -f 1,2,3,4,5| sed -n '2p' `
PATH3=` ls -ltr /app/dre/thirdparty/apache-tomcat-9.0.10/webapps| awk '{print $11}'| sed '1d'|sed -n -e 1p -e 3p -e 5p -e 7p|cut -d/ -f 1,2,3,4,5| sed -n '3p' `
PATH4=` ls -ltr /app/dre/thirdparty/apache-tomcat-9.0.10/webapps| awk '{print $11}'| sed '1d'|sed -n -e 1p -e 3p -e 5p -e 7p|cut -d/ -f 1,2,3,4,5| sed -n '4p' `
PID=` ps -ef | grep 'apache-tomcat-9.0.10' | grep java | grep -v grep | awk '{ print $2 }' `
printf '1. Start\n'
printf '2. Shutdown\n'

        while true; do
        read NUM
        case $NUM in
        1)
                D1=` cat current | sed -n -e 1p `; D2=` cat current | sed -n -e 2p `; D3=` cat current | sed -n -e 3p `; D4=` cat current | sed -n -e 4p `;
                C1=` cat current |cut -d/ -f 5|sed -n -e 1p `; C2=` cat current |cut -d/ -f 5|sed -n -e 2p `;C3=` cat current |cut -d/ -f 5|sed -n -e 3p `; C4=` cat current |cut -d/ -f 5|sed -n -e 4p`;
                VARFILE1=` grep -is using /app/var/lsurf/log/$C1/control-script.log| tail -n 1| awk '{print $2}' `
                VARFILE2=` grep -is using /app/var/lsurf/log/$C2/control-script.log| tail -n 1| awk '{print $2}' `
                VARFILE3=` grep -is using /app/var/lsurf/log/$C3/control-script.log| tail -n 1| awk '{print $2}' `
                VARFILE4=` grep -is using /app/var/lsurf/log/$C4/control-script.log| tail -n 1| awk '{print $2}' `

                printf "Type S to start the tomcat \nType D to deploy apps\nType E for exit\n"
                        while read OPTION;do
                        case $OPTION in
                          S)
                                printf "############Starting tomcat.Please monitor the logs############\n";
                                /app/dre/thirdparty/apache-tomcat-9.0.10/bin/startup.sh;
                                printf 'Type D to deploy apps.Type E to exit\n';continue;
                                ;;
                          D)
                                printf 'Hello Ops,\n Which app do you want me to deploy?\nSelect the number\n';echo -e "1. $C1";echo -e "2. $C2";echo -e "3. $C3";echo -e "4. $C4";
                        while read SELECT;do

    case $SELECT in
     1)
          echo "Identifying env-var file";
          echo "Last used var file is $VARFILE1";
          echo "**************************Deploying $CMD1***************************";
          cd $D1/bin;
          ./upd-env $VARFILE1;
          echo -e "2. $C2";echo -e "3. $C3";echo -e "4. $C4";echo "Type E to exit";continue;
          ;;


2)
          echo "Identifying env-var file";
          echo "Last used var file is $VARFILE2";
          echo "**************************Deploying $CMD2***************************";
          cd $D2/bin;
          ./upd-env $VARFILE2;
          echo -e "3. $C3";echo -e "4. $C4";echo "Type E to exit";continue;
          ;;
     3)
          echo "Identifying env-var file";
          echo "Last used var file is $VARFILE3";
          echo "**************************Deploying $CMD3***************************";
          cd $D3/bin;
          ./upd-env $VARFILE3;
          echo -e "4. $C4";echo "Type E to exit";continue;
          ;;
     4)
          echo "Identifying env-var file";
          echo "Last used var file is $VARFILE4";
          echo "**************************Deploying $CMD4***************************";
          cd $D4/bin;
          ./upd-env $VARFILE4;
          ;;
     E)
          exit 0
          ;;
     *)
          echo "There is no such package.Please select the valid option or type E to exit";continue
          ;;
        esac
        break
        done;;
                E)
                        exit 0
                        ;;

                *)
                        echo "Invalid selection.Please select the valid option or type E to exit";continue
                        ;;
                  esac
                  break
                  done;;
        2)
echo "$PATH1" > current;echo "$PATH2" >> current;echo "$PATH3" >> current;echo "$PATH4" >> current
                printf "Type S to shutdown the tomcat \nType R to remove the packages\nType E for exit\n"
                        while read SHUTDOWN;do
                        case $SHUTDOWN in
                          S)
                                printf "############Shutting down tomcat.Please monitor the logs############\n";
                                /app/dre/thirdparty/apache-tomcat-9.0.10/bin/shutdown.sh;
                                printf '******Please wait for 15 seconds******\n'
                                        sleep 15;
                                        if [[ $(ps -ef | grep 'apache-tomcat-9.0.10' | grep java | grep -v grep | awk '{ print $2 }') ]];then
                                        printf "TOMCAT is still running\n";
                                        printf "Type K to kill the tomcat forcefully\nType E for exit\n";
                                        while true; do
                                                read TOM
                                                case $TOM in
                                                        K)
                                                                kill $PID
                                                                ;;
                                                        E)
                                                                exit 0
                                                                ;;
                                                        *)
                                                                echo "Invalid selection.Please select the valid option or type E to exit";continue;
                                                                ;;
                                         esac
                                         break
                                         done

                                else
                                        echo "TOMCAT is stopped";
                                fi
                                printf 'Type R to remove the packages.Type E to exit\n';continue;
                                ;;
                          R)
                                printf 'Removing packages\n';
                                rm -rf /app/dre/thirdparty/apache-tomcat-9.0.10/webapps/*
                                ;;
                          E)
                                exit 0
                                ;;
						  *)
                                echo "Invalid selection.Please select the valid option or type E to exit";continue;
                                ;;
                        esac
                        break
                        done;;
  esac
  break
 done
